### ISSUE TITLE
Figma: formulários

### ISSUE THREAD

**Issue by paulo-granthon** [projetoKhali/api4front#51]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Criar design das telas de listagem enquanto os formulários de inserção estiverem sendo exibidos; 

# Motivação:
`Por que precisamos dessa mudança?`

- Definir visual a ser seguido durante desenvolvimento;
- Representar a tela que será trabalhada para a aprovação do cliente;

**Comment by NicSouza** [comment]
![Image](https://github.com/projetoKhali/api4front/assets/108769169/10d94483-491b-4899-a112-d66e1326eaf4)
