### ISSUE TITLE
Draft das telas de dashboard comparativo

### ISSUE THREAD

**Issue by paulo-granthon** [projetoKhali/api4front#65]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Estipular quais gráficos estarão presentes nas telas de dashboard comparativo de `Track` e `Partner`.

# Motivação:
`Por que precisamos dessa mudança?`

- Aliviar a responsabilidade de quem for fazer o Figma de pensar em quais gráficos estarão presentes nas telas.

# Critérios de aceite:
`Quais parâmetros devem ser atendidos?`

- todo!()

**Comment by Incivius** [comment]
> 

[Comparativo.drawio (1).pdf](https://github.com/projetoKhali/api4front/files/15282859/Comparativo.drawio.1.pdf)
