### ISSUE TITLE
Componente `Stacked bar chart`

### ISSUE THREAD

**Issue by Incivius** [projetoKhali/api4front#79]
# Necessidade:
`Qual iniciativa precisa ser trabalhada?`

- Criar um componente gráfico de barras empilhadas para utilizar no dashboard comparativos entre partners.

# Motivação:
`Por que precisamos dessa mudança?`

- Vamos utilizar esse gráfico por fornecer uma melhor visualização dos insights que queremos disponibilizar nessa pagina;

# Critérios de aceite:
`Quais parâmetros devem ser atendidos?`

- Cada barra vai representar um parceiro, ao criar a barra vamos precisar passar 3 paramentos: Total de expertises da track, total de expertises em progresso pelo parceiro e total de expertises finalizadas por aquele parceiro. 
O gráfico deve esperar receber os seguintes valores:
> Uma label
> Array de string que será renderizado como as label do eixo X, cada item do array será um parceir;
> Um ou mais array de number, cada array será um nova barra e os valores dele definirão as barras empilhas

Exemplo:

label: Track Shell
Array de string: ['Marcos', 'Tania', 'Paulo']
array de number: [ [22, 10, 5], [22, 13, 8], [22, 9, 8] ]

# Sugestões:
`Observações para obter mais facilidade e / ou qualidade na implementação`

Exemplo dos dados que ele deve receber:

label: Track Shell
Array de string: ['Marcos', 'Tania', 'Paulo']
array de number: [ [22, 10, 5], [22, 13, 8], [22, 9, 8] ]

Grafico esperado:

![image](https://github.com/projetoKhali/api4front/assets/111438883/4d70c422-93ab-45a5-889a-f4cd4b445371)

**Comment by JhonatanLop** [comment]
maior parte do gráfico foi finalizado:

![image](https://github.com/projetoKhali/api4front/assets/111443621/331c5f55-ae17-4787-a8a1-c6d7b37ca12e)

tive que fazer alterações no input dos dados para evitar que o cálculo do tamanho das barras fique a cargo do componente.

props do componente:
```typescript
const props = defineProps({
    title: {
        type: String,
        required: true
    },
    itens: {
        type: Array<String>,
        required: true
    },
    data: {
        type: Array<Array<Number>>,
        required: true
    },
    height: {
        type: Array<Array<number>>,
        required: true
    }
})
```

Para o cálculo da altura das barras foi criado uma constante que retorna um Array de Array de Number com a medida das barras.

formato de input de dados.

```typescript
const title = 'Track Shell'
const itens = ['Marcos', 'Tania', 'Paulo']
const data = [[22, 10, 5], [22, 13, 8], [22, 9, 8]]
const height = (() => {
    const heightList = [];
    for (let i = 0; i < data.length; i++) {
        const listAtIndex = [];
        const dataAtIndex = data[i]!;
        for (let j = 0; j < dataAtIndex.length; j++) {
            if (!dataAtIndex || !dataAtIndex[j]) {
                continue;
            }
            const total = dataAtIndex.reduce((a, b) => a + b, 0);
            const dataAtSegment = dataAtIndex[j];
            
            if (!total || !dataAtSegment) {
                continue;
            }
            const segmentHeight = (dataAtSegment / total) * 100;
            listAtIndex.push(segmentHeight);
        }
        heightList.push(listAtIndex);
    }
    return heightList;
})();
```
O calculo da constante deve ser o mesmo usado no exemplo `StackedBarChartDemonstrate`
